#!/usr/bin/env python3
"""
copy_attributes.py
Lists all attributes and their respective values, for selected object. Disregards attribute types: message, compound.
"""
import maya.cmds as cmds

ATTRIBUTES = {'affectAlpha': 'affects_alpha',
              'affectShadows': 'affects_alpha',
              'anisotropy': 'anisotropy_orientation',
              'anisotropyAxis': 'anisotropy_orientation',
              'anisotropyDerivation': 'anisotropy_orientation',
              'anisotropyRotation': 'anisotropy_orientation',
              'attributeAliasList': 'coat_reflectivity',
              'binMembership': 'binMembership',
              'brdfType': 'refl_brdf',
              'bumpDeltaScale': 'ms_radius_scale',
              'bumpMap': 'bump_input',
              'bumpMapB': 'bump_inputB',
              'bumpMapG': 'bump_inputG',
              'bumpMapR': 'bump_inputR',
              'bumpMapType': 'outApiType',
              'bumpMult': 'bump_input',
              'bumpShadows': 'ms_radius0',
              'caching': 'caching',
              'color': 'outColor',
              'compensateExposure': 'coat_bump_inputR',
              'cutoffThreshold': 'coat_fresnel_mode',
              'diffuseColorAmount': 'diffuse_color',
              'diffuseColorB': 'diffuse_colorB',
              'diffuseColorG': 'diffuse_colorG',
              'diffuseColorR': 'diffuse_colorR',
              'doubleSided': 'depth_override',
              'fixDarkEdges': 'refl_indirect',
              'fogBias': 'refl_roughness',
              'fogColor': 'outColor',
              'fogColorB': 'outColorB',
              'fogColorG': 'outColorG',
              'fogColorR': 'outColorR',
              'fogMult': 'outColor',
              'fresnelIOR': 'refl_ior',
              'frozen': 'frozen',
              'ggxOldTailFalloff': 'outApiClassification',
              'ggxTailFalloff': 'outApiClassification',
              'glossyFresnel': 'refl_fresnel_mode',
              'hilightGlossiness': 'refl_isGlossiness',
              'hilightGlossinessLock': 'refl_isGlossiness',
              'illumColor': 'outColor',
              'illumColorB': 'outColorB',
              'illumColorG': 'outColorG',
              'illumColorR': 'outColorR',
              'illumGI': 'block_volumes',
              'isHistoricallyInteresting': 'isHistoricallyInteresting',
              'lockFresnelIORToRefractionIOR': 'refl_aniso_rotation',
              'metalness': 'refl_metalness',
              'nodeState': 'nodeState',
              'opacityMap': 'opacity_color',
              'opacityMapB': 'opacity_colorB',
              'opacityMapG': 'opacity_colorG',
              'opacityMapR': 'opacity_color',
              'opacityMode': 'opacity_color',
              'outApiClassification': 'outApiClassification',
              'outApiType': 'outApiType',
              'outColor': 'outColor',
              'outColorB': 'outColorB',
              'outColorG': 'outColorG',
              'outColorR': 'outColorR',
              'outTransparency': 'coat_transmittance',
              'outTransparencyB': 'coat_transmittanceB',
              'outTransparencyG': 'coat_transmittanceG',
              'outTransparencyR': 'coat_transmittanceR',
              'reflInterpolation': 'refl_aniso_rotation',
              'reflMapColorThreshold': 'refl_colorR',
              'reflMapMaxRate': 'refl_samples',
              'reflMapMinRate': 'refl_indirect',
              'reflMapNormalThreshold': 'refl_aniso_rotation',
              'reflMapSamples': 'refl_samples',
              'reflectOnBackSide': 'refl_endmode',
              'reflectionAffectAlpha': 'affects_alpha',
              'reflectionColor': 'refl_color',
              'reflectionColorAmount': 'refl_weight',
              'reflectionColorB': 'refl_colorB',
              'reflectionColorG': 'refl_colorG',
              'reflectionColorR': 'refl_colorR',
              'reflectionDimDistance': 'refr_transmittance',
              'reflectionDimDistanceOn': 'refr_transmittance',
              'reflectionDimFallOff': 'refl_enablecutoff',
              'reflectionExitColor': 'refl_color',
              'reflectionExitColorB': 'refl_colorB',
              'reflectionExitColorG': 'refl_colorG',
              'reflectionExitColorR': 'refl_colorR',
              'reflectionGlossiness': 'refl_isGlossiness',
              'reflectionSubdivs': 'refl_metalness',
              'reflectionsMaxDepth': 'refl_depth',
              'refrDispersionAbbe': 'refr_abbe',
              'refrDispersionOn': 'refr_samples',
              'refrInterpolation': 'refl_aniso_rotation',
              'refrMapColorThreshold': 'refr_colorR',
              'refrMapMaxRate': 'refr_samples',
              'refrMapMinRate': 'refr_absorption_scale',
              'refrMapNormalThreshold': 'refr_samples',
              'refrMapSamples': 'refr_samples',
              'refractionColor': 'refr_color',
              'refractionColorAmount': 'refr_weight',
              'refractionColorB': 'refr_colorB',
              'refractionColorG': 'refr_colorG',
              'refractionColorR': 'refr_colorR',
              'refractionExitColor': 'refr_color',
              'refractionExitColorB': 'refr_colorB',
              'refractionExitColorG': 'refr_colorG',
              'refractionExitColorOn': 'refr_color',
              'refractionExitColorR': 'refr_colorR',
              'refractionGlossiness': 'refr_isGlossiness',
              'refractionIOR': 'refr_color',
              'refractionSubdivs': 'refr_absorption_scale',
              'refractionsMaxDepth': 'refr_depth',
              'roughnessAmount': 'ss_amount',
              'scatterCoeff': 'ss_scatter_coeff',
              'scatterDir': 'ss_scatter_coeffR',
              'scatterLevels': 'ss_scatter_coeff',
              'scatterSubdivs': 'ss_scatter_coeffB',
              'softenEdge': 'coat_fresnel_mode',
              'sssEnvironment': 'sheen_direct',
              'sssOn': 'ss_amount',
              'swatchAlwaysRender': 'isHistoricallyInteresting',
              'swatchAutoUpdate': 'shaderNodeTemplate',
              'swatchExplicitUpdate': 'shaderNodeTemplate',
              'swatchMaxRes': 'ss_samples',
              'thickness': 'coat_thickness',
              'traceReflections': 'refl_reflectivity',
              'traceRefractions': 'refr_absorption_scale',
              'translucencyColor': 'transl_color',
              'translucencyColorB': 'transl_colorB',
              'translucencyColorG': 'transl_colorG',
              'translucencyColorR': 'transl_colorR',
              'useFresnel': 'refl_fresnel_mode',
              'useIrradianceMap': 'refr_transmittance',
              'useRoughness': 'diffuse_roughness'}
ATTRIBUTES_VRAY = {'affectAlpha': 'affectAlpha',
                   'affectShadows': 'affectShadows',
                   'anisotropy': 'anisotropy',
                   'anisotropyAxis': 'anisotropyAxis',
                   'anisotropyDerivation': 'anisotropyDerivation',
                   'anisotropyRotation': 'anisotropyRotation',
                   'attributeAliasList': 'attributeAliasList',
                   'binMembership': 'binMembership',
                   'brdfType': 'brdfType',
                   'bumpDeltaScale': 'bumpDeltaScale',
                   'bumpMap': 'bumpMap',
                   'bumpMapB': 'bumpMapB',
                   'bumpMapG': 'bumpMapG',
                   'bumpMapR': 'bumpMapR',
                   'bumpMapType': 'bumpMapType',
                   'bumpMult': 'bumpMult',
                   'bumpShadows': 'bumpShadows',
                   'caching': 'caching',
                   'color': 'color',
                   'compensateExposure': 'compensateExposure',
                   'cutoffThreshold': 'cutoffThreshold',
                   'diffuseColorAmount': 'diffuseColorAmount',
                   'diffuseColorB': 'diffuseColorB',
                   'diffuseColorG': 'diffuseColorG',
                   'diffuseColorR': 'diffuseColorR',
                   'doubleSided': 'doubleSided',
                   'fixDarkEdges': 'fixDarkEdges',
                   'fogBias': 'fogBias',
                   'fogColor': 'fogColor',
                   'fogColorB': 'fogColorB',
                   'fogColorG': 'fogColorG',
                   'fogColorR': 'fogColorR',
                   'fogMult': 'fogMult',
                   'fresnelIOR': 'fresnelIOR',
                   'frozen': 'frozen',
                   'ggxOldTailFalloff': 'ggxOldTailFalloff',
                   'ggxTailFalloff': 'ggxTailFalloff',
                   'glossyFresnel': 'glossyFresnel',
                   'hilightGlossiness': 'hilightGlossiness',
                   'hilightGlossinessLock': 'hilightGlossinessLock',
                   'illumColor': 'illumColor',
                   'illumColorB': 'illumColorB',
                   'illumColorG': 'illumColorG',
                   'illumColorR': 'illumColorR',
                   'illumGI': 'illumGI',
                   'isHistoricallyInteresting': 'isHistoricallyInteresting',
                   'lockFresnelIORToRefractionIOR': 'lockFresnelIORToRefractionIOR',
                   'metalness': 'metalness',
                   'nodeState': 'nodeState',
                   'notes': 'notes',
                   'opacityMap': 'opacityMap',
                   'opacityMapB': 'opacityMapB',
                   'opacityMapG': 'opacityMapG',
                   'opacityMapR': 'opacityMapR',
                   'opacityMode': 'opacityMode',
                   'outApiClassification': 'outApiClassification',
                   'outApiType': 'outApiType',
                   'outColor': 'outColor',
                   'outColorB': 'outColorB',
                   'outColorG': 'outColorG',
                   'outColorR': 'outColorR',
                   'outTransparency': 'outTransparency',
                   'outTransparencyB': 'outTransparencyB',
                   'outTransparencyG': 'outTransparencyG',
                   'outTransparencyR': 'outTransparencyR',
                   'reflInterpolation': 'reflInterpolation',
                   'reflMapColorThreshold': 'reflMapColorThreshold',
                   'reflMapMaxRate': 'reflMapMaxRate',
                   'reflMapMinRate': 'reflMapMinRate',
                   'reflMapNormalThreshold': 'reflMapNormalThreshold',
                   'reflMapSamples': 'reflMapSamples',
                   'reflectOnBackSide': 'reflectOnBackSide',
                   'reflectionAffectAlpha': 'reflectionAffectAlpha',
                   'reflectionColor': 'reflectionColor',
                   'reflectionColorAmount': 'reflectionColorAmount',
                   'reflectionColorB': 'reflectionColorB',
                   'reflectionColorG': 'reflectionColorG',
                   'reflectionColorR': 'reflectionColorR',
                   'reflectionDimDistance': 'reflectionDimDistance',
                   'reflectionDimDistanceOn': 'reflectionDimDistanceOn',
                   'reflectionDimFallOff': 'reflectionDimFallOff',
                   'reflectionExitColor': 'reflectionExitColor',
                   'reflectionExitColorB': 'reflectionExitColorB',
                   'reflectionExitColorG': 'reflectionExitColorG',
                   'reflectionExitColorR': 'reflectionExitColorR',
                   'reflectionGlossiness': 'reflectionGlossiness',
                   'reflectionSubdivs': 'reflectionSubdivs',
                   'reflectionsMaxDepth': 'reflectionsMaxDepth',
                   'refrDispersionAbbe': 'refrDispersionAbbe',
                   'refrDispersionOn': 'refrDispersionOn',
                   'refrInterpolation': 'refrInterpolation',
                   'refrMapColorThreshold': 'refrMapColorThreshold',
                   'refrMapMaxRate': 'refrMapMaxRate',
                   'refrMapMinRate': 'refrMapMinRate',
                   'refrMapNormalThreshold': 'refrMapNormalThreshold',
                   'refrMapSamples': 'refrMapSamples',
                   'refractionColor': 'refractionColor',
                   'refractionColorAmount': 'refractionColorAmount',
                   'refractionColorB': 'refractionColorB',
                   'refractionColorG': 'refractionColorG',
                   'refractionColorR': 'refractionColorR',
                   'refractionExitColor': 'refractionExitColor',
                   'refractionExitColorB': 'refractionExitColorB',
                   'refractionExitColorG': 'refractionExitColorG',
                   'refractionExitColorOn': 'refractionExitColorOn',
                   'refractionExitColorR': 'refractionExitColorR',
                   'refractionGlossiness': 'refractionGlossiness',
                   'refractionIOR': 'refractionIOR',
                   'refractionSubdivs': 'refractionSubdivs',
                   'refractionsMaxDepth': 'refractionsMaxDepth',
                   'roughnessAmount': 'roughnessAmount',
                   'scatterCoeff': 'scatterCoeff',
                   'scatterDir': 'scatterDir',
                   'scatterLevels': 'scatterLevels',
                   'scatterSubdivs': 'scatterSubdivs',
                   'softenEdge': 'softenEdge',
                   'sssEnvironment': 'sssEnvironment',
                   'sssOn': 'sssOn',
                   'swatchAlwaysRender': 'swatchAlwaysRender',
                   'swatchAutoUpdate': 'swatchAutoUpdate',
                   'swatchExplicitUpdate': 'swatchExplicitUpdate',
                   'swatchMaxRes': 'swatchMaxRes',
                   'thickness': 'thickness',
                   'traceReflections': 'traceReflections',
                   'traceRefractions': 'traceRefractions',
                   'translucencyColor': 'translucencyColor',
                   'translucencyColorB': 'translucencyColorB',
                   'translucencyColorG': 'translucencyColorG',
                   'translucencyColorR': 'translucencyColorR',
                   'useFresnel': 'useFresnel',
                   'useIrradianceMap': 'useIrradianceMap',
                   'useRoughness': 'useRoughness'}
REDSHIFT_ATTRIBUTES = {'affects_alpha': 'affects_alpha',
                       'anisotropy_orientation': 'anisotropy_orientation',
                       'binMembership': 'binMembership',
                       'block_volumes': 'block_volumes',
                       'bump_input': 'bump_input',
                       'bump_inputB': 'bump_inputB',
                       'bump_inputG': 'bump_inputG',
                       'bump_inputR': 'bump_inputR',
                       'caching': 'caching',
                       'coat_brdf': 'coat_brdf',
                       'coat_bump_input': 'coat_bump_input',
                       'coat_bump_inputB': 'coat_bump_inputB',
                       'coat_bump_inputG': 'coat_bump_inputG',
                       'coat_bump_inputR': 'coat_bump_inputR',
                       'coat_color': 'coat_color',
                       'coat_colorB': 'coat_colorB',
                       'coat_colorG': 'coat_colorG',
                       'coat_colorR': 'coat_colorR',
                       'coat_direct': 'coat_direct',
                       'coat_fresnel_mode': 'coat_fresnel_mode',
                       'coat_indirect': 'coat_indirect',
                       'coat_ior': 'coat_ior',
                       'coat_ior3': 'coat_ior3',
                       'coat_ior30': 'coat_ior30',
                       'coat_ior31': 'coat_ior31',
                       'coat_ior32': 'coat_ior32',
                       'coat_isGlossiness': 'coat_isGlossiness',
                       'coat_reflectivity': 'coat_reflectivity',
                       'coat_reflectivityB': 'coat_reflectivityB',
                       'coat_reflectivityG': 'coat_reflectivityG',
                       'coat_reflectivityR': 'coat_reflectivityR',
                       'coat_roughness': 'coat_roughness',
                       'coat_samples': 'coat_samples',
                       'coat_thickness': 'coat_thickness',
                       'coat_transmittance': 'coat_transmittance',
                       'coat_transmittanceB': 'coat_transmittanceB',
                       'coat_transmittanceG': 'coat_transmittanceG',
                       'coat_transmittanceR': 'coat_transmittanceR',
                       'coat_weight': 'coat_weight',
                       'combined_depth': 'combined_depth',
                       'decoupleIORFromRoughness': 'decoupleIORFromRoughness',
                       'depth_override': 'depth_override',
                       'diffuse_color': 'diffuse_color',
                       'diffuse_colorB': 'diffuse_colorB',
                       'diffuse_colorG': 'diffuse_colorG',
                       'diffuse_colorR': 'diffuse_colorR',
                       'diffuse_direct': 'diffuse_direct',
                       'diffuse_indirect': 'diffuse_indirect',
                       'diffuse_roughness': 'diffuse_roughness',
                       'diffuse_weight': 'diffuse_weight',
                       'emission_color': 'emission_color',
                       'emission_colorB': 'emission_colorB',
                       'emission_colorG': 'emission_colorG',
                       'emission_colorR': 'emission_colorR',
                       'emission_weight': 'emission_weight',
                       'energyCompMode': 'energyCompMode',
                       'frozen': 'frozen',
                       'isHistoricallyInteresting': 'isHistoricallyInteresting',
                       'ms_amount': 'ms_amount',
                       'ms_color0': 'ms_color0',
                       'ms_color0B': 'ms_color0B',
                       'ms_color0G': 'ms_color0G',
                       'ms_color0R': 'ms_color0R',
                       'ms_color1': 'ms_color1',
                       'ms_color1B': 'ms_color1B',
                       'ms_color1G': 'ms_color1G',
                       'ms_color1R': 'ms_color1R',
                       'ms_color2': 'ms_color2',
                       'ms_color2B': 'ms_color2B',
                       'ms_color2G': 'ms_color2G',
                       'ms_color2R': 'ms_color2R',
                       'ms_include_mode': 'ms_include_mode',
                       'ms_mode': 'ms_mode',
                       'ms_radius0': 'ms_radius0',
                       'ms_radius1': 'ms_radius1',
                       'ms_radius2': 'ms_radius2',
                       'ms_radius_scale': 'ms_radius_scale',
                       'ms_samples': 'ms_samples',
                       'ms_weight0': 'ms_weight0',
                       'ms_weight1': 'ms_weight1',
                       'ms_weight2': 'ms_weight2',
                       'nodeState': 'nodeState',
                       'opacity_color': 'opacity_color',
                       'opacity_colorB': 'opacity_colorB',
                       'opacity_colorG': 'opacity_colorG',
                       'opacity_colorR': 'opacity_colorR',
                       'outApiClassification': 'outApiClassification',
                       'outApiType': 'outApiType',
                       'outColor': 'outColor',
                       'outColorB': 'outColorB',
                       'outColorG': 'outColorG',
                       'outColorR': 'outColorR',
                       'overallAffectsEmission': 'overallAffectsEmission',
                       'overall_color': 'overall_color',
                       'overall_colorB': 'overall_colorB',
                       'overall_colorG': 'overall_colorG',
                       'overall_colorR': 'overall_colorR',
                       'preset': 'preset',
                       'refl_aniso': 'refl_aniso',
                       'refl_aniso_rotation': 'refl_aniso_rotation',
                       'refl_brdf': 'refl_brdf',
                       'refl_color': 'refl_color',
                       'refl_colorB': 'refl_colorB',
                       'refl_colorG': 'refl_colorG',
                       'refl_colorR': 'refl_colorR',
                       'refl_cutoff': 'refl_cutoff',
                       'refl_depth': 'refl_depth',
                       'refl_direct': 'refl_direct',
                       'refl_edge_tint': 'refl_edge_tint',
                       'refl_edge_tintB': 'refl_edge_tintB',
                       'refl_edge_tintG': 'refl_edge_tintG',
                       'refl_edge_tintR': 'refl_edge_tintR',
                       'refl_enablecutoff': 'refl_enablecutoff',
                       'refl_endmode': 'refl_endmode',
                       'refl_fresnel_mode': 'refl_fresnel_mode',
                       'refl_indirect': 'refl_indirect',
                       'refl_ior': 'refl_ior',
                       'refl_ior3': 'refl_ior3',
                       'refl_ior30': 'refl_ior30',
                       'refl_ior31': 'refl_ior31',
                       'refl_ior32': 'refl_ior32',
                       'refl_isGlossiness': 'refl_isGlossiness',
                       'refl_k3': 'refl_k3',
                       'refl_k30': 'refl_k30',
                       'refl_k31': 'refl_k31',
                       'refl_k32': 'refl_k32',
                       'refl_metalness': 'refl_metalness',
                       'refl_reflectivity': 'refl_reflectivity',
                       'refl_reflectivityB': 'refl_reflectivityB',
                       'refl_reflectivityG': 'refl_reflectivityG',
                       'refl_reflectivityR': 'refl_reflectivityR',
                       'refl_roughness': 'refl_roughness',
                       'refl_samples': 'refl_samples',
                       'refl_weight': 'refl_weight',
                       'refr_abbe': 'refr_abbe',
                       'refr_absorption_scale': 'refr_absorption_scale',
                       'refr_color': 'refr_color',
                       'refr_colorB': 'refr_colorB',
                       'refr_colorG': 'refr_colorG',
                       'refr_colorR': 'refr_colorR',
                       'refr_cutoff': 'refr_cutoff',
                       'refr_depth': 'refr_depth',
                       'refr_enablecutoff': 'refr_enablecutoff',
                       'refr_ior': 'refr_ior',
                       'refr_isGlossiness': 'refr_isGlossiness',
                       'refr_roughness': 'refr_roughness',
                       'refr_samples': 'refr_samples',
                       'refr_thin_walled': 'refr_thin_walled',
                       'refr_transmittance': 'refr_transmittance',
                       'refr_transmittanceB': 'refr_transmittanceB',
                       'refr_transmittanceG': 'refr_transmittanceG',
                       'refr_transmittanceR': 'refr_transmittanceR',
                       'refr_use_base_IOR': 'refr_use_base_IOR',
                       'refr_weight': 'refr_weight',
                       'shaderNodeTemplate': 'shaderNodeTemplate',
                       'shadow_opacity': 'shadow_opacity',
                       'sheen_color': 'sheen_color',
                       'sheen_colorB': 'sheen_colorB',
                       'sheen_colorG': 'sheen_colorG',
                       'sheen_colorR': 'sheen_colorR',
                       'sheen_direct': 'sheen_direct',
                       'sheen_indirect': 'sheen_indirect',
                       'sheen_isGlossiness': 'sheen_isGlossiness',
                       'sheen_roughness': 'sheen_roughness',
                       'sheen_samples': 'sheen_samples',
                       'sheen_weight': 'sheen_weight',
                       'skip_inside_refl': 'skip_inside_refl',
                       'ss_amount': 'ss_amount',
                       'ss_extinction_coeff': 'ss_extinction_coeff',
                       'ss_extinction_coeffB': 'ss_extinction_coeffB',
                       'ss_extinction_coeffG': 'ss_extinction_coeffG',
                       'ss_extinction_coeffR': 'ss_extinction_coeffR',
                       'ss_extinction_scale': 'ss_extinction_scale',
                       'ss_phase': 'ss_phase',
                       'ss_samples': 'ss_samples',
                       'ss_scatter_coeff': 'ss_scatter_coeff',
                       'ss_scatter_coeffB': 'ss_scatter_coeffB',
                       'ss_scatter_coeffG': 'ss_scatter_coeffG',
                       'ss_scatter_coeffR': 'ss_scatter_coeffR',
                       'ss_unitsMode': 'ss_unitsMode',
                       'transl_color': 'transl_color',
                       'transl_colorB': 'transl_colorB',
                       'transl_colorG': 'transl_colorG',
                       'transl_colorR': 'transl_colorR',
                       'transl_weight': 'transl_weight',
                       'uvSet': 'uvSet',
                       'version': 'version'}
VRAYMTL_DEFAULTS = {
    'caching': False,
    'frozen': False,
    'isHistoricallyInteresting': 2,
    'nodeState': 0,
    'binMembership': None,
    'outColor': [(0.5, 0.5, 0.5)],
    'outColorR': 0.5,
    'outColorG': 0.5,
    'outColorB': 0.5,
    'outApiType': 'VRayMtl',
    'outApiClassification': 'shader/surface/utility/:rendernode/vray/shader/surface/utility/:drawdb/shader/surface/VRayMtlShader:swatch/VRayMtlSwatchGen',
    'outTransparency': [(0.0, 0.0, 0.0)],
    'outTransparencyR': 0.0,
    'outTransparencyG': 0.0,
    'outTransparencyB': 0.0,
    'reflectionsMaxDepth': 5,
    'refractionsMaxDepth': 5,
    'swatchAutoUpdate': True,
    'swatchAlwaysRender': False,
    'swatchExplicitUpdate': 0,
    'swatchMaxRes': 64,
    'color': [(0.5, 0.5, 0.5)],
    'diffuseColorR': 0.5,
    'diffuseColorG': 0.5,
    'diffuseColorB': 0.5,
    'diffuseColorAmount': 1.0,
    'roughnessAmount': 0.0,
    'illumColor': [(0.0, 0.0, 0.0)],
    'illumColorR': 0.0,
    'illumColorG': 0.0,
    'illumColorB': 0.0,
    'illumGI': False,
    'compensateExposure': False,
    'reflectionColor': [(0.0, 0.0, 0.0)],
    'reflectionColorR': 0.0,
    'reflectionColorG': 0.0,
    'reflectionColorB': 0.0,
    'reflectionColorAmount': 1.0,
    'reflectionExitColor': [(0.0, 0.0, 0.0)],
    'reflectionExitColorR': 0.0,
    'reflectionExitColorG': 0.0,
    'reflectionExitColorB': 0.0,
    'hilightGlossinessLock': True,
    'hilightGlossiness': 1.0,
    'reflectionGlossiness': 1.0,
    'reflectionSubdivs': 8,
    'reflectionAffectAlpha': 0,
    'reflInterpolation': False,
    'reflMapMinRate': -1,
    'reflMapMaxRate': -1,
    'reflMapColorThreshold': 0.25,
    'reflMapNormalThreshold': 0.40000000596,
    'reflMapSamples': 20,
    'useFresnel': True,
    'lockFresnelIORToRefractionIOR': True,
    'fresnelIOR': 1.60000002384,
    'reflectOnBackSide': False,
    'softenEdge': 0.0,
    'fixDarkEdges': True,
    'glossyFresnel': True,
    'ggxTailFalloff': 2.0,
    'ggxOldTailFalloff': False,
    'metalness': 0.0,
    'useRoughness': False,
    'anisotropy': 0.0,
    'anisotropyRotation': 0.0,
    'anisotropyDerivation': 0,
    'anisotropyAxis': 2,
    'refractionColor': [(0.0, 0.0, 0.0)],
    'refractionColorR': 0.0,
    'refractionColorG': 0.0,
    'refractionColorB': 0.0,
    'refractionColorAmount': 1.0,
    'refractionExitColor': [(0.0, 0.0, 0.0)],
    'refractionExitColorR': 0.0,
    'refractionExitColorG': 0.0,
    'refractionExitColorB': 0.0,
    'refractionExitColorOn': False,
    'refractionGlossiness': 1.0,
    'refractionSubdivs': 8,
    'refractionIOR': 1.60000002384,
    'refrDispersionOn': False,
    'refrDispersionAbbe': 50.0,
    'refrInterpolation': False,
    'refrMapMinRate': -1,
    'refrMapMaxRate': -1,
    'refrMapColorThreshold': 0.25,
    'refrMapNormalThreshold': 0.40000000596,
    'refrMapSamples': 20,
    'fogColor': [(1.0, 1.0, 1.0)],
    'fogColorR': 1.0,
    'fogColorG': 1.0,
    'fogColorB': 1.0,
    'fogMult': 1.0,
    'fogBias': 0.0,
    'affectShadows': True,
    'affectAlpha': 0,
    'traceReflections': True,
    'traceRefractions': True,
    'cutoffThreshold': 0.0010000000475,
    'brdfType': 3,
    'bumpMapType': 0,
    'bumpMap': [(0.0, 0.0, 0.0)],
    'bumpMapR': 0.0,
    'bumpMapG': 0.0,
    'bumpMapB': 0.0,
    'bumpMult': 1.0,
    'bumpShadows': False,
    'bumpDeltaScale': 1.0,
    'sssOn': False,
    'translucencyColor': [(1.0, 1.0, 1.0)],
    'translucencyColorR': 1.0,
    'translucencyColorG': 1.0,
    'translucencyColorB': 1.0,
    'thickness': 1000.0,
    'scatterCoeff': 0.0,
    'scatterDir': 1.0,
    'scatterLevels': 1,
    'scatterSubdivs': 8,
    'sssEnvironment': False,
    'opacityMap': [(1.0, 1.0, 1.0)],
    'opacityMapR': 1.0,
    'opacityMapG': 1.0,
    'opacityMapB': 1.0,
    'opacityMode': 2,
    'doubleSided': True,
    'useIrradianceMap': True,
    'reflectionDimDistanceOn': False,
    'reflectionDimDistance': 100.0,
    'reflectionDimFallOff': 0.0,
    'attributeAliasList': None
}
REDSHIFTMTL_DEFAULTS = {'affects_alpha': True,
 'anisotropy_orientation': 2,
 'binMembership': None,
 'block_volumes': True,
 'bump_input': [(0.0, 0.0, 0.0)],
 'bump_inputB': 0.0,
 'bump_inputG': 0.0,
 'bump_inputR': 0.0,
 'caching': False,
 'coat_brdf': 0,
 'coat_bump_input': [(0.0, 0.0, 0.0)],
 'coat_bump_inputB': 0.0,
 'coat_bump_inputG': 0.0,
 'coat_bump_inputR': 0.0,
 'coat_color': [(1.0, 1.0, 1.0)],
 'coat_colorB': 1.0,
 'coat_colorG': 1.0,
 'coat_colorR': 1.0,
 'coat_direct': 1.0,
 'coat_fresnel_mode': 3,
 'coat_indirect': 1.0,
 'coat_ior': 1.399999976158142,
 'coat_ior3': [(1.399999976158142, 1.399999976158142, 1.399999976158142)],
 'coat_ior30': 1.399999976158142,
 'coat_ior31': 1.399999976158142,
 'coat_ior32': 1.399999976158142,
 'coat_isGlossiness': False,
 'coat_reflectivity': [(0.027000000700354576,
                        0.027000000700354576,
                        0.027000000700354576)],
 'coat_reflectivityB': 0.027000000700354576,
 'coat_reflectivityG': 0.027000000700354576,
 'coat_reflectivityR': 0.027000000700354576,
 'coat_roughness': 0.0,
 'coat_samples': 16,
 'coat_thickness': 0.10000000149011612,
 'coat_transmittance': [(1.0, 1.0, 1.0)],
 'coat_transmittanceB': 1.0,
 'coat_transmittanceG': 1.0,
 'coat_transmittanceR': 1.0,
 'coat_weight': 0.0,
 'combined_depth': 6,
 'decoupleIORFromRoughness': False,
 'depth_override': False,
 'diffuse_color': [(0.5, 0.5, 0.5)],
 'diffuse_colorB': 0.5,
 'diffuse_colorG': 0.5,
 'diffuse_colorR': 0.5,
 'diffuse_direct': 1.0,
 'diffuse_indirect': 1.0,
 'diffuse_roughness': 0.0,
 'diffuse_weight': 1.0,
 'emission_color': [(0.0, 0.0, 0.0)],
 'emission_colorB': 0.0,
 'emission_colorG': 0.0,
 'emission_colorR': 0.0,
 'emission_weight': 0.0,
 'energyCompMode': 1,
 'frozen': False,
 'isHistoricallyInteresting': 2,
 'ms_amount': 0.0,
 'ms_color0': [(1.0, 0.8999999761581421, 0.699999988079071)],
 'ms_color0B': 0.699999988079071,
 'ms_color0G': 0.8999999761581421,
 'ms_color0R': 1.0,
 'ms_color1': [(1.0, 0.8999999761581421, 0.699999988079071)],
 'ms_color1B': 0.699999988079071,
 'ms_color1G': 0.8999999761581421,
 'ms_color1R': 1.0,
 'ms_color2': [(1.0, 0.8999999761581421, 0.699999988079071)],
 'ms_color2B': 0.699999988079071,
 'ms_color2G': 0.8999999761581421,
 'ms_color2R': 1.0,
 'ms_include_mode': 1,
 'ms_mode': 1,
 'ms_radius0': 1.0,
 'ms_radius1': 1.0,
 'ms_radius2': 1.0,
 'ms_radius_scale': 1.0,
 'ms_samples': 64,
 'ms_weight0': 1.0,
 'ms_weight1': 0.0,
 'ms_weight2': 0.0,
 'nodeState': 0,
 'opacity_color': [(1.0, 1.0, 1.0)],
 'opacity_colorB': 1.0,
 'opacity_colorG': 1.0,
 'opacity_colorR': 1.0,
 'outApiClassification': 'drawdb/shader/surface/RedshiftMaterial:shader/surface:rendernode/redshift/shader/surface:swatch/RedshiftSwatchGen',
 'outApiType': 'RedshiftMaterial',
 'outColor': [(0.5, 0.5, 0.5)],
 'outColorB': 0.5,
 'outColorG': 0.5,
 'outColorR': 0.5,
 'overallAffectsEmission': False,
 'overall_color': [(1.0, 1.0, 1.0)],
 'overall_colorB': 1.0,
 'overall_colorG': 1.0,
 'overall_colorR': 1.0,
 'preset': -1,
 'refl_aniso': 0.0,
 'refl_aniso_rotation': 0.0,
 'refl_brdf': 0,
 'refl_color': [(1.0, 1.0, 1.0)],
 'refl_colorB': 1.0,
 'refl_colorG': 1.0,
 'refl_colorR': 1.0,
 'refl_cutoff': 0.009999999776482582,
 'refl_depth': 3,
 'refl_direct': 1.0,
 'refl_edge_tint': [(0.0, 0.0, 0.0)],
 'refl_edge_tintB': 0.0,
 'refl_edge_tintG': 0.0,
 'refl_edge_tintR': 0.0,
 'refl_enablecutoff': False,
 'refl_endmode': 1,
 'refl_fresnel_mode': 3,
 'refl_indirect': 1.0,
 'refl_ior': 1.5,
 'refl_ior3': [(1.5, 1.5, 1.5)],
 'refl_ior30': 1.5,
 'refl_ior31': 1.5,
 'refl_ior32': 1.5,
 'refl_isGlossiness': False,
 'refl_k3': [(0.0, 0.0, 0.0)],
 'refl_k30': 0.0,
 'refl_k31': 0.0,
 'refl_k32': 0.0,
 'refl_metalness': 0.0,
 'refl_reflectivity': [(0.03999999910593033,
                        0.03999999910593033,
                        0.03999999910593033)],
 'refl_reflectivityB': 0.03999999910593033,
 'refl_reflectivityG': 0.03999999910593033,
 'refl_reflectivityR': 0.03999999910593033,
 'refl_roughness': 0.0,
 'refl_samples': 16,
 'refl_weight': 1.0,
 'refr_abbe': 0.0,
 'refr_absorption_scale': 1.0,
 'refr_color': [(1.0, 1.0, 1.0)],
 'refr_colorB': 1.0,
 'refr_colorG': 1.0,
 'refr_colorR': 1.0,
 'refr_cutoff': 0.009999999776482582,
 'refr_depth': 5,
 'refr_enablecutoff': False,
 'refr_ior': 1.5,
 'refr_isGlossiness': False,
 'refr_roughness': 0.0,
 'refr_samples': 8,
 'refr_thin_walled': False,
 'refr_transmittance': [(1.0, 1.0, 1.0)],
 'refr_transmittanceB': 1.0,
 'refr_transmittanceG': 1.0,
 'refr_transmittanceR': 1.0,
 'refr_use_base_IOR': True,
 'refr_weight': 0.0,
 'shaderNodeTemplate': 'Material',
 'shadow_opacity': 0.0,
 'sheen_color': [(1.0, 1.0, 1.0)],
 'sheen_colorB': 1.0,
 'sheen_colorG': 1.0,
 'sheen_colorR': 1.0,
 'sheen_direct': 1.0,
 'sheen_indirect': 1.0,
 'sheen_isGlossiness': False,
 'sheen_roughness': 0.30000001192092896,
 'sheen_samples': 64,
 'sheen_weight': 0.0,
 'skip_inside_refl': True,
 'ss_amount': 0.0,
 'ss_extinction_coeff': [(0.0, 0.0, 0.0)],
 'ss_extinction_coeffB': 0.0,
 'ss_extinction_coeffG': 0.0,
 'ss_extinction_coeffR': 0.0,
 'ss_extinction_scale': 1.0,
 'ss_phase': 0.0,
 'ss_samples': 16,
 'ss_scatter_coeff': [(1.0, 1.0, 1.0)],
 'ss_scatter_coeffB': 1.0,
 'ss_scatter_coeffG': 1.0,
 'ss_scatter_coeffR': 1.0,
 'ss_unitsMode': 0,
 'transl_color': [(0.5, 0.5, 0.5)],
 'transl_colorB': 0.5,
 'transl_colorG': 0.5,
 'transl_colorR': 0.5,
 'transl_weight': 0.0,
 'uvSet': None,
 'version': 1}


# def main():
#     """docstring for main"""
#     nodes = cmds.ls(sl=True)
#     source = nodes[0]
#     dest = nodes[1]
#
#     attribute_list = cmds.listAttr(source)
#     for attr in attribute_list:
#         if '.' not in attr:
#             attribute_type = cmds.attributeQuery(attr, node=source, at=True)
#             if attribute_type not in ['message', 'compound']:
#                 attribute_value = cmds.getAttr('{}.{}'.format(source, attr))
#                 try:
#                     cmds.setAttr('{}.{}'.format(dest, ATTRIBUTES[attr]))
#                 except Exception as e:
#                     print(e)
#

def main():
    nodes = cmds.ls(sl=True)
    vray_mtl = nodes[0]
    redshift_mtl = cmds.shadingNode('RedshiftMaterial', asShader=True)

    attributes = cmds.listAttr(vray_mtl)
    for attribute in attributes:
        if '.' not in attribute:
            attribute_type = cmds.attributeQuery(attribute, node=vray_mtl, at=True)
            if attribute_type not in ['message', 'compound']:
                value = cmds.getAttr('{}.{}'.format(vray_mtl, attribute))
                try:
                    redshift_attribute = '{}.{}'.format(redshift_mtl, ATTRIBUTES[attribute])
                    cmds.setAttr(redshift_attribute, value)
                    print('{} set to {}'.format(redshift_attribute, value))
                except Exception as e:
                    print(e)
    return


if __name__ == '__main__':
    main()
