#!/usr/bin/env python3
"""fix_color_space.py
Description of fix_color_space.py.
"""
import logging
from maya import cmds

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(name)s %(levelname)s:%(message)s')
logger = logging.getLogger(__name__)
IGNORE = ['initialShadingGroup', 'initialShadingGroup', 'initialParticleSE', 'lambert1']

COLOR_SPACES = {'diffuse_color': 'sRGB',
                'refl_roughness': 'Raw',
                'refl_aniso_rotation': 'Raw',
                'bump_input': 'Raw',
                'refl_metalness': 'Raw'}


def get_inputs(node):
    """Get all input connections for a node

    Args:
        node: input node

    Returns:
        dict: input connections and nodes
    """
    inputs = {node: {}}
    if not node in IGNORE:
        # logger.info(f'Connections to {node}')
        conn = cmds.listConnections(node, s=True, d=False, c=True)
        if conn:
            for i in range(len(conn)):
                if i % 2 == 0:
                    conn_in = conn[i].split('.')[-1]
                    conn_out = conn[i + 1]
                    inputs[node]['type'] = cmds.nodeType(node)

                    if not inputs[node].get('connections'):
                        inputs[node]['connections'] = {}
                    if not conn_in.endswith('.message'):
                        # logger.info(f'{conn_in}: {conn_out}')
                        inputs[node]['connections'][conn_in] = get_inputs(conn_out)
                    else:
                        inputs[node]['connections'][conn_in] = conn_out

    return inputs


def change_colorspace(node, color_space):
    """Change the colorspace of a node

    Args:
        node: file node
        color_space: chosen color space

    Returns:

    """
    has_colorspace = cmds.attributeQuery('colorSpace', node=node, ex=True)
    attrib = node + '.colorSpace'

    if has_colorspace:
        cmds.setAttr(attrib, color_space, type='string')

    return cmds.getAttr(attrib)


def process_tree(tree, color_space='Raw'):
    """Process a dict of nodes and connections

    Args:
        tree: dict with nodes and connections. Generated by get_inputs()
        color_space: The chosen color space for the node
    """
    node = list(tree)[0]
    node_type = tree[node].get('type')

    # Check if the key has a node type or it's just a connection
    if node_type:
        if node_type == 'file':
            logger.info(f'Changing {node} input color space to {color_space}')
            change_colorspace(node, color_space)
        for k, v in tree[node].get('connections', {}).items():
            process_tree(v)


def main():
    """docstring for main"""
    all_materials = cmds.ls(mat=True)

    for material in all_materials:
        logger.info(f'Processing inputs for {material}')
        inputs = get_inputs(material)

        for k, v in inputs[material].get('connections', {}).items():
            # Determine color space
            clr_space = COLOR_SPACES.get(k, 'Raw')
            logger.info(f'Changing all file input color spaces for {k} to {clr_space}')

            # Process connections
            process_tree(v, clr_space)

        print('')


if __name__ == '__main__':
    main()
